apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: common
spec:
  storageClassName: local-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi