apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: common
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      name: kafka
      targetPort: 9092
      nodePort: 30091
      protocol: TCP
  selector:
    app: kafka