apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: common
data:
  MODE: 'standalone'
  MYSQL_SERVICE_DB_NAME: 'nacos'
  MYSQL_SERVICE_HOST: '10.98.75.250'
  MYSQL_SERVICE_PASSWORD: '123456'
  MYSQL_SERVICE_PORT: '3306'
  MYSQL_SERVICE_USER: 'root'
  SPRING_DATASOURCE_PLATFORM: 'mysql'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: common
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: docker.repo.kpy.cloud/kpybase/nacos-server:1.1.4
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: nacos-config
          ports:
            - containerPort: 8848
#          resources:
#            requests:
#              memory: 1Gi
#            limits:
#              memory: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: nacos
  namespace: common
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
  type: NodePort
