apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: common
spec:
  selector:
    app: rabbitmq
  ports:
    - name: admin
      port: 15672
    - name: client
      port: 5672
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: common
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-alpine
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: rabbitmq
