apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: common
spec:
  selector:
    app: redis
  ports:
    - port: 6379
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: common
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.7
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/data"
              name: redis-persistent-storage
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: host-pvc
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis
