apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-ha-server-config
  namespace: common
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = "nacos"
          namespace = "c601726f-fd3e-452b-88d0-3f8c86c471c7"
        }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "nacos"
        group = "SEATA_GROUP"
        namespace = "776171c6-84d5-4d61-8edf-4ddb66579ed5"
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: seata-ha-server
  namespace: common
  labels:
    app.kubernetes.io/name: seata-ha-server
spec:
#  type: ClusterIP
  type: NodePort
  ports:
    - port: 8091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: seata-ha-server

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-ha-server
  namespace: common
  labels:
    app.kubernetes.io/name: seata-ha-server
spec:
  serviceName: seata-ha-server
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-ha-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-ha-server
    spec:
      containers:
        - name: seata-ha-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-ha-server-config

